package com.hust.common.base.enums;

public enum TemplateField {
    OTP_CODE,
    _USERNAME_,
    TIMESTAMP,
    PASSWORD,
    DAY,
    ACCOUNT_NUMBER,
    EMAIL,
    LINK_WEB_PUBLIC_TOKEN,
    TRANSACTION_TIME,
    PAYMENT_ACCOUNT,
    TRANSACTION_AMOUNT,
    CURRENCY,
    SOURCE_ACCOUNT,
    BANK_CODE,
    MESSAGE,
    TRANSACTION_CODE,
    BENEFICIARY_ACCOUNT,
    LABEL_PAYMENT_ACCOUNT,
    LABEL_TRANSACTION_AMOUNT,
    LABEL_CONTENT_TRANSACTION,
    CONTENT_TRANSACTION
}
